import hashlib
import json
import logging
from datetime import datetime, timezone
import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from typing import Dict, Any

logger = logging.getLogger(__name__)

class LegalCertification:
    def __init__(self):
        self.cert_dir = "backend/legal_audits"
        if not os.path.exists(self.cert_dir):
            os.makedirs(self.cert_dir)

    def generate_integrity_hash(self, payload: Dict[str, Any]) -> str:
        """
        Generates a SHA-256 integrity hash of a JSON payload.
        Ensures keys are sorted for deterministic hashing.
        """
        payload_str = json.dumps(payload, sort_keys=True)
        return hashlib.sha256(payload_str.encode('utf-8')).hexdigest()

    def generate_65b_certificate(
        self, 
        applicant_id: str, 
        osint_payload: Dict[str, Any], 
        digi_payload: Dict[str, Any],
        device_ip: str = "127.0.0.1"
    ) -> str:
        """
        Generates a legally compliant PDF certificate under Section 65B 
        of the Indian Evidence Act, 1872 / Sec 61 BSA, 2023.
        """
        timestamp = datetime.now(timezone.utc).isoformat()
        osint_hash = self.generate_integrity_hash(osint_payload)
        digi_hash = self.generate_integrity_hash(digi_payload)
        
        cert_filename = f"65B_Certificate_{applicant_id}_{int(datetime.now().timestamp())}.pdf"
        cert_path = os.path.join(self.cert_dir, cert_filename)
        
        try:
            c = canvas.Canvas(cert_path, pagesize=letter)
            c.setFont("Helvetica-Bold", 14)
            c.drawString(100, 750, "CERTIFICATE UNDER SECTION 65B OF THE INDIAN EVIDENCE ACT, 1872")
            c.drawString(100, 730, "AND SECTION 61 OF BHARATIYA SAKSHYA ADHINIYAM (BSA), 2023")
            
            c.setFont("Helvetica", 10)
            c.drawString(100, 690, "This is to certify that the digital records pertaining to the OSINT and Identity Verification")
            c.drawString(100, 675, f"for Applicant ID: {applicant_id} were generated by a computer system in the")
            c.drawString(100, 660, "ordinary course of lawful activities.")
            
            c.drawString(100, 620, "1. Chain of Custody & Metadata:")
            c.drawString(120, 605, f"Timestamp of Acquisition: {timestamp}")
            c.drawString(120, 590, f"Acquiring Device IP: {device_ip}")
            
            c.drawString(100, 550, "2. Cryptographic Integrity Hashes (SHA-256):")
            c.drawString(120, 535, f"OSINT Payload Hash:")
            c.setFont("Helvetica", 8)
            c.drawString(120, 525, f"{osint_hash}")
            
            c.setFont("Helvetica", 10)
            c.drawString(120, 500, f"DigiVerifier Payload Hash:")
            c.setFont("Helvetica", 8)
            c.drawString(120, 490, f"{digi_hash}")
            
            c.setFont("Helvetica", 10)
            c.drawString(100, 450, "3. Declaration:")
            c.drawString(120, 435, "I certify that to the best of my knowledge, the computer system was operating")
            c.drawString(120, 420, "properly at the time the records were generated, and the integrity of the data")
            c.drawString(120, 405, "has been preserved via cryptographic hashing immediately upon acquisition.")
            
            c.drawString(100, 350, "Authorized Signatory: ___________________________")
            c.drawString(100, 330, "Automated AIDUS Legal Admissibility Module")
            
            c.save()
            logger.info(f"Generated 65B Certificate at {cert_path}")
            return cert_path
        except Exception as e:
            logger.error(f"Failed to generate 65B certificate: {e}")
            return ""

legal_certification = LegalCertification()
